### PR TITLE
Fix auto-instantiation failing on extra parentheses 

### PR DESCRIPTION
**Pull request by richzwart**
Now with all the original spaces in included comments!

### CODE REVIEW

**Comment by joecrop** [comment]
@richzwart  I cleaned up the tests and pushed to your branch. There is only one failing now, and I think it is "real". It looks like there is a port being added with the name  "2+2" and the rest of the instantiation is missing.

```diff
       test #9: formatInstance with brackets in parameter default value:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual
- expected

+ 'azzer u_azzer (\n  .1+1    (1+1)\n);'
- 'azzer #(\n' +
-   '  .SIZE        ((2*1)+1),\n' +
-   '  .SIZE_TWO    (2*(1+1))\n' +
-   ') u_azzer (\n' +
-   '  .clk         (clk),\n' +
-   '  .reset       (reset),\n' +
-   '  .a           (a),\n' +
-   '  .b           (b),\n' +
-   '  .valid       (valid),\n' +
-   '  .c           (c)\n' +
-   ');'

+ expected
- actual

-      azzer u_azzer (
-        .1+1    (1+1)
+      azzer #(
+        .SIZE        ((2*1)+1),
+        .SIZE_TWO    (2*(1+1))
+      ) u_azzer (
+        .clk         (clk),
+        .reset       (reset),
+        .a           (a),
+        .b           (b),
+        .valid       (valid),
+        .c           (c)
       );
```

**Comment by richzwart** [comment]
I'm on it.

**Comment by richzwart** [comment]
I can't seem to reproduce the error in "Client+Server" debug, but I do see
it show up in the npm run tests.
Any ideas?

Rich

**Comment by joecrop** [comment]
Hmm, this usually happens when the file positions are off when reading the files into the test case. Let me see what my client+server does.

**Comment by joecrop** [comment]
yeah, client+server works for me, must be a file position issue in the test case.

**Comment by joecrop** [comment]
So, the isModuleParameterized call is failing to return true on line 261 of ModuleInstantiator.ts. I tihnk that is the crux of the problem. Please try runnign the debugger:
1. In VSCode, change the debug run option to "Extension Tests"
2. Add a breakpoint somewhere in test 9.
3. Hit the run button
4. Step through the code and see what is happening to the call to isModuleParameterizes.

P.S. The inputs look correct on first inspection. Perhaps there is an issue with newlines (/r/n) etc.?

**Pull request merged**
