### PR TITLE
Live Syntax Error Identification and LSP improvements

### PR DESCRIPTION
**Pull request by ForrestHurley**
This pull request extends the system to allow for the use of an LSP implementation that uses an ANTLR-generated SystemVerilog parser to check for syntax errors. This is an improvement over using regular expressions and symbol tables in terms of its accuracy. It also does not require the use of external simulator such as Verilator.

The ANTLR grammar files are included, and the parser is generated on compilation, so a user can modify the grammar if they want. This will affect what is considered a syntax error by our new code. There is also an option which allows you to disable the LSP/ANTLR system independently of the rest of the extension. We added slightly less than 20 unit and integration tests to verify correct functioning of our new features.

The parsing functionality is an important step towards supporting autocompleting variable ranges as in #47. By parsing the full syntax, it becomes fairly straightforward to identify variable ranges.

We worked with Chris Dietsch to develop this feature.

### CODE REVIEW

**Comment by ForrestHurley** [comment]
The files in /compiling/ANTLR/grammar describe the grammar and are used to generate typescript files for the parser. They must be built by running `npm run compile` (this is automatically done for `npm test`, but I'm not certain that it is automatic for debugging the extension normally)

**Comment by eirikpre** [comment]
Oh my, this is a great amount of content!
Let me start by saying this is fantastic, and will definitively be pulled in, and should be expanded on, and replace the current parser.
However, I am currently away on Conference and it's amidst tapeout times, so it might take a while for me to pull it in.

One question of the top of my head(didn't have time to dig in the code):
- Go to Symbols (in document/workspace) is what seems to be the most utilized features now (before completion). Is there a way to control the granularity of the parser, to be able to more efficiently parse workspace symbols? Both for time and memory requirements. Or maybe there is not that much of a difference when use ANTLR?

Good to hear from you, I haven't heard anything from Chris since the one mention of you in an email half a year ago.

**Comment by cdietschrun** [comment]
Hey Eirik, sorry for the big drop of a PR :D 

I've been working with these folks as part of a university project for those months, and we were preparing for something along these lines. Sorry for the radio silence, but it was just a lot of research and ideas and implementation. 

I'll let the students reply to your technical question, and totally understand regarding your current schedule. We just wanted to try to get this PR out there as they develop some more features to not have one giant PR that also includes more changes to the extension before getting this one to your eyes to discuss.

I'm really impressed with their work so far and think this is a nugget of an idea that can be expanded upon for both performance and features.

**Comment by eirikpre** [comment]
Alright, I've had a very brief look at it. Looks very good!
I want to pull it in, but I want it to integrate smoothly and quietly so that it will not blow up for all the users if we decide to publish anytime soon. Perhaps the default value `systemverilog.antlrVerification` can be `false` as a nice middle ground. As far as I understood, it will still run onDidChange even if the setting above is `false`

Some annoyances/incompatibility issues I noticed:
- It seems the json protocol sending text does escape the text. This leads to the error reporting being misaligned. I would suggest that only URIs are passed across the protocol and the server will open the file.
- The parser is triggered on any onDidChange/onDidOpen event in the workspace. The indexer, even though I assume we will replace this some time, also triggers these events when looking through files. This leads to _indexing_ being performed both by RegExp parser and ANTLR parser.
- A lot of extraneous messages :)

Here is a direction to what can be done to listen to only window onDidOpen [from API](https://code.visualstudio.com/api/references/vscode-api#workspace):
image

**Comment by eirikpre** [comment]
Merged it, I hope that I'm not stalling you in any way.

Additional remark, won't the macro expansion make it hard to find the origin line/character when reading back the parser results?

**Pull request merged**
